scheduler API improvements and static healthcheck

diff --git a/Dockerfiles/base-builder/bin/ignis-sshserver b/Dockerfiles/base-builder/bin/ignis-sshserver
--- a/Dockerfiles/base-builder/bin/ignis-sshserver
+++ b/Dockerfiles/base-builder/bin/ignis-sshserver
@@ -9,63 +9,64 @@ H_TIMEOUT=${IGNIS_HEALTHCHECK_TIMEOUT}
 H_RETRIES=${IGNIS_HEALTHCHECK_RETRIES}
 H_URL=${IGNIS_HEALTHCHECK_URL}
 
-
-
 sleep inf & FD=/proc/$!/fd
 export IGNIS_JOB_STDOUT=${FD}/1
 export IGNIS_JOB_STDERR=${FD}/2
 
-export IGNIS_CONTAINER_DIR=${IGNIS_TMPDIR}/${IGNIS_JOB_ID}/tmp/${IGNIS_CONTAINER_ID}/
-SSH_DIR=${IGNIS_CONTAINER_DIR}/ssh
+SSH_DIR=${IGNIS_JOB_CONTAINER_DIR}/ssh
 mkdir -p -m 700 ${SSH_DIR}
 export -p > ${CONTAINER_FOLDER}/environment
-mkdir -m 700 ${IGNIS_CONTAINER_DIR}/sockets
+mkdir -m 700 ${IGNIS_JOB_CONTAINER_DIR}/sockets
 
 cp /etc/ssh/sshd_config ${SSH_DIR}
 chmod 644 ${SSH_DIR}/sshd_config
 ssh-keygen -q -N "" -t rsa -b 2048 -f ${SSH_DIR}/ssh_host_rsa_key
 
 if [ "${MODE}" == "driver" ]; then
-  EXTRA_ARGS="-d -o ForceCommand='touch ${IGNIS_CONTAINER_DIR}/ready;\$SSH_ORIGINAL_COMMAND'"
+  EXTRA_ARGS="-d -o ForceCommand='touch ${IGNIS_JOB_CONTAINER_DIR}/ready;\$SSH_ORIGINAL_COMMAND'"
 fi
 
 sshd(){
-    /usr/bin/sshd -p $1 \
-                  -c "${CONFIG_SSH}/sshd_config" \
-                  -h "${CONFIG_SSH}/ssh_host_rsa_key" \
-                  -e ${EXTRA_ARGS} \
-                  -D 2>&1 | grep -v "^Server listening" > ${CONFIG_SSH}/check & SSHD_PID=$!
+  /usr/bin/sshd -p $1 \
+                -c "${CONFIG_SSH}/sshd_config" \
+                -h "${CONFIG_SSH}/ssh_host_rsa_key" \
+                -e ${EXTRA_ARGS} \
+                -D 2>&1 | grep -v "^Server listening" > ${CONFIG_SSH}/check & SSHD_PID=$!
 }
 
 host_sshd(){
   BASE=$(shuf -i 1-64000 -n 1)
   for i in 1...64000; do
     PORT=$((($BASE+$i)%64000+1024))
-    sshd $PORT
+    sshd ${PORT}
     while [ -e "/proc/${SSHD_PID}" ]; do
       if grep -q "Server listening on" ${CONFIG_SSH}/check; then
         break 2
       fi
+      sleep 1
     done
   done
 }
 
-if [ "$PORT" == "0" ];then
-  sshd $PORT
+if [ "${PORT}" == "0" ];then
+  sshd ${PORT}
 else
   host_sshd
-  if [ "$IGNIS_DISCOVERY_TYPE" == "file" ]; then
-    echo $PORT > $IGNIS_DISCOVERY_TARGET
-  elif [ "$IGNIS_DISCOVERY_TYPE" == "url" ]; then #TODO etcd
-    URL=$IGNIS_DISCOVERY_TARGET
-    if [ -z "${IGNIS_CRYPTO_SECRET}"]; then
-      URL=$(ignis-crypto decode ${IGNIS_CRYPTO_SECRET} <<<${URL}))
-    fi
-    for i in {1..${H_RETRIES}}; do
-      curl --output /dev/null --silent --head --fail -H "PORT:$PORT" -H "INDEX:${!IGNIS_SCHEDULER_INDEX}" \
-           --connect-timeout ${H_TIMEOUT} ${URL} && \
-      s=0 && break || s=$? && sleep ${H_INTERVAL}
-    done
+  if [ "${IGNIS_DISCOVERY_TYPE}" == "file" ]; then
+    echo "${HOST_HOSTNAME}:${PORT}" > ${IGNIS_JOB_CONTAINER_DIR}/discovery
+  elif [ "${IGNIS_DISCOVERY_TYPE}" == "etcd" ]; then #TODO etcd
+
+
+
+    #URL=$IGNIS_DISCOVERY_TARGET
+    #if [ -n "${IGNIS_CRYPTO_SECRET}"]; then
+    #  URL=$(ignis-crypto decode ${IGNIS_CRYPTO_SECRET} <<<${URL}))
+    #fi
+    #for i in {1..${H_RETRIES}}; do
+    #  curl --output /dev/null --silent --head --fail -H "PORT:$PORT" -H "INDEX:${!IGNIS_SCHEDULER_INDEX}" \
+    #       --connect-timeout ${H_TIMEOUT} ${URL} && \
+    #  s=0 && break || s=$? && sleep ${H_INTERVAL}
+    #done
     if [ "$s" != "0" ];then
       echo "Failed to connect to $URL" 1>&2
       exit $s
@@ -76,14 +77,14 @@ trap "exit 0" TERM
 if [ "${MODE}" == "driver" ]; then
   echo "Waiting client connection" 1>&2
   sleep 60
-  if [ ! -f ${IGNIS_CONTAINER_DIR}/ready ]; then
+  if [ ! -f ${IGNIS_JOB_CONTAINER_DIR}/ready ]; then
     echo "Client connection timeout" 1>&2
     exit -1
   fi
   wait ${SSHD_PID}
   echo "Client disconnected" 1>&2
   exit 0
-elif [ "${MODE}" == "executor" ]; then
+elif [ "${MODE}" == "executor" ] && [ -z "${IGNIS_HEALTHCHECK_DISABLE}" ]; then
   while true; do
     for i in {1..${H_RETRIES}}; do
       curl --output /dev/null --silent --head --fail --connect-timeout ${H_TIMEOUT} ${H_URL} && \
